import type { Metadata } from "next";
import { Archivo, Geist, Geist_Mono, Inter } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Lenis from "@/components/providers/Lenis";
import Navbar from "@/components/site/layout/Navbar";

const archivoHeading = Archivo({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
        archivoHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Lenis>
          <Navbar />
          {children}
        </Lenis>
      </body>
    </html>
  );
}
